# Generated by Django 5.2.17 on 2026-08-13 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=120)),
                ('emoji', models.CharField(default='🏅', max_length=8)),
                ('kind', models.CharField(choices=[('streak', 'Day streak'), ('total_drills', 'Drills completed'), ('skills_tried', 'Skills tried'), ('total_minutes', 'Minutes trained'), ('weak_foot', 'Weak foot drills')], max_length=20)),
                ('threshold', models.PositiveIntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'threshold'],
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('instructions', models.TextField(help_text='Two or three short sentences, written for Will to read himself.')),
                ('cue', models.CharField(help_text="One coaching cue, e.g. 'head up'.", max_length=60)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('needs_ball', models.BooleanField(default=True)),
                ('needs_wall', models.BooleanField(default=False)),
                ('needs_cones', models.BooleanField(default=False)),
                ('needs_space', models.BooleanField(default=False)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('weak_foot', models.BooleanField(default=False, help_text='Explicitly works the weaker foot.')),
                ('is_fun', models.BooleanField(default=False, help_text='A fun finisher or freestyle drill.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['skill__order', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('label', models.CharField(max_length=60)),
                ('is_rest', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False, help_text='Academy or match day - the session is a bonus, not expected.')),
                ('target_minutes', models.PositiveSmallIntegerField(default=25)),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('emoji', models.CharField(default='⚽', help_text='Shown next to the skill name.', max_length=8)),
                ('colour', models.CharField(default='#7bdc3f', help_text='Hex colour for progress bars.', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_uses', to='training.drill')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.planday')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='drill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drills', to='training.skill'),
        ),
        migrations.AddField(
            model_name='planday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.trainingplan'),
        ),
        migrations.CreateModel(
            name='EarnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='training.badge')),
            ],
            options={
                'ordering': ['-earned_on'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'badge'), name='one_award_per_badge')],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=True)),
                ('actual_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Really hard'), (2, 'Hard'), (3, 'OK'), (4, 'Good'), (5, 'Easy')], help_text='How did that feel?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='training.drill')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date', 'drill'), name='one_log_per_drill_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='drill',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_minutes__isnull', False), ('target_reps__isnull', True)), models.Q(('duration_minutes__isnull', True), ('target_reps__isnull', False)), _connector='OR'), name='drill_has_duration_or_reps_not_both'),
        ),
        migrations.AddConstraint(
            model_name='planday',
            constraint=models.UniqueConstraint(fields=('plan', 'weekday'), name='one_planday_per_weekday'),
        ),
    ]
