# Generated by Django 5.2.17 on 2026-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='colour',
            field=models.CharField(default='#2a78d6', help_text='Hex colour for progress bars.', max_length=7),
        ),
    ]
