# Generated by Django 5.2.17 on 2026-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_skill_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='kind',
            field=models.CharField(choices=[('streak', 'Day streak'), ('total_drills', 'Drills completed'), ('skills_tried', 'Skills tried'), ('total_minutes', 'Minutes trained'), ('weak_foot', 'Weak foot drills'), ('perfect_weeks', 'Perfect weeks')], max_length=20),
        ),
    ]
