# Generated by Django 5.2.17 on 2026-08-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_badge_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planday',
            name='target_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
