# Generated by Django 5.2.17 on 2026-08-26 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_plan_day_target_thirty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='is_juggling',
            field=models.BooleanField(default=False, help_text='Juggling or keepy-ups. Every session has one.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='kind',
            field=models.CharField(choices=[('streak', 'Day streak'), ('total_drills', 'Drills completed'), ('skills_tried', 'Skills tried'), ('total_minutes', 'Minutes trained'), ('weak_foot', 'Weak foot drills'), ('juggling', 'Juggling drills'), ('perfect_weeks', 'Perfect weeks')], max_length=20),
        ),
        migrations.CreateModel(
            name='SessionClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_clocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'date'), name='one_clock_per_day')],
            },
        ),
    ]
