# Generated by Django 5.2.17 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_drill_is_juggling_alter_badge_kind_sessionclock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandrill',
            options={'ordering': ['week', 'order', 'pk']},
        ),
        migrations.AddField(
            model_name='plandrill',
            name='week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Every week'), (1, 'Week A'), (2, 'Week B')], default=0, help_text='Which week of the fortnight this drill is part of.'),
        ),
    ]
