# Generated by Django 5.2.17 on 2026-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_plandrill_options_plandrill_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='is_combination',
            field=models.BooleanField(default=False, help_text='A sequence of moves joined together, not one move repeated.'),
        ),
    ]
