# Generated by Django 5.2.17 on 2026-10-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_drill_is_combination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "pack",
                    models.CharField(
                        choices=[
                            ("quick-feet", "Quick feet"),
                            ("combos", "Combos"),
                            ("moves", "Moves"),
                            ("rebounder", "Rebounder"),
                            ("dribbling", "Dribbling"),
                            ("finishing", "Finishing"),
                            ("keepy-ups", "Keepy-ups"),
                            ("free-play", "Free play"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Two or three short sentences, written for Will to read himself."
                    ),
                ),
                (
                    "cue",
                    models.CharField(
                        help_text="One cue about the result, not the body.",
                        max_length=60,
                    ),
                ),
                (
                    "scoring",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("time", "Time"),
                            ("none", "No score"),
                        ],
                        default="count",
                        max_length=8,
                    ),
                ),
                (
                    "score_label",
                    models.CharField(
                        blank=True,
                        help_text="What the number means, e.g. 'taps'.",
                        max_length=60,
                    ),
                ),
                (
                    "per_foot",
                    models.BooleanField(
                        default=False,
                        help_text="Scored weak foot first, then strong foot.",
                    ),
                ),
                (
                    "out_of",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The most he can score, if there is one.",
                        null=True,
                    ),
                ),
                (
                    "timer_seconds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Length of a 'how many in N seconds' go.",
                        null=True,
                    ),
                ),
                ("bronze", models.PositiveIntegerField(blank=True, null=True)),
                ("silver", models.PositiveIntegerField(blank=True, null=True)),
                ("gold", models.PositiveIntegerField(blank=True, null=True)),
                ("move", models.CharField(blank=True, max_length=40)),
                ("level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("needs_cones", models.BooleanField(default=False)),
                ("needs_rebounder", models.BooleanField(default=False)),
                ("needs_goal", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Play",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                (
                    "played_at",
                    models.DateTimeField(help_text="When the phone says it happened."),
                ),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("weak_score", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plays",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plays",
                        to="training.card",
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
    ]
