# Generated by Django 5.2.17 on 2026-10-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='bests',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Feet that beat his best (0-2); a first score is not one.', null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='medal',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'None'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold')], null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
