# Generated by Django 5.2.17 on 2026-10-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_play_stamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='kind',
            field=models.CharField(choices=[('streak', 'Day streak'), ('total_drills', 'Drills completed'), ('skills_tried', 'Skills tried'), ('total_minutes', 'Minutes trained'), ('weak_foot', 'Weak foot drills'), ('juggling', 'Juggling drills'), ('perfect_weeks', 'Perfect weeks'), ('goal_weeks_run', 'Goal weeks in a row'), ('goal_weeks_total', 'Goal weeks in total'), ('move_golds', 'Move golds'), ('personal_bests', 'Personal bests'), ('test_weeks', 'Test weeks done'), ('weak_foot_closer', 'Weak foot closer'), ('free_plays', 'Free play')], max_length=20),
        ),
    ]
